### ISSUE TITLE
Using other steemd

### ISSUE THREAD

**Issue by mostar** [xeroc/piston#13]
When I point to my steemd it fail on:

piston list --sort created --limit 20

```
Traceback (most recent call last):
  File "/usr/local/bin/piston", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/piston/__main__.py", line 733, in main
    start=args.start
  File "/usr/local/lib/python3.4/dist-packages/piston/steem.py", line 715, in get_posts
    for p in func(discussion_query):
  File "/usr/local/lib/python3.4/dist-packages/grapheneapi/graphenewsrpc.py", line 373, in method
    r = self.rpcexec(query)
  File "/usr/local/lib/python3.4/dist-packages/grapheneapi/graphenewsrpc.py", line 340, in rpcexec
    raise err
  File "/usr/local/lib/python3.4/dist-packages/grapheneapi/graphenewsrpc.py", line 336, in rpcexec
    raise RPCError(ret['error']['message'])
grapheneapi.graphenewsrpc.RPCError: 10 assert_exception: Assert Exception
_index[space_id].size() > type_id: 
    {"space_id":5,"type_id":3,"index[space_id].size":0}
    th_a  object_database.cpp:57 get_index
```

I can see it comunicate in my steemd output

```
7282ms th_a       database_api.cpp:180          database_api_impl    ] creating database api 1601780752
2967283ms th_a       websocket_api.cpp:88          on_message           ] message: {"jsonrpc": "2.0", "id": 1, "method": "call", "params": [1, "login", ["", ""]]} 
2967283ms th_a       api.cpp:56                    login                ] user:  password:  
2967283ms th_a       api.cpp:72                    login                ] acc->allowed_apis: ["database_api","network_broadcast_api","tag_api"] 
2967283ms th_a       api.cpp:82                    login                ] known api: database_api
2967283ms th_a       api.cpp:85                    login                ] api_name: network_broadcast_api 
2967283ms th_a       api.cpp:85                    login                ] api_name: tag_api 
2967283ms th_a       application.cpp:379           create_api_by_name   ] unknown api: tag_api
2967283ms th_a       websocket_api.cpp:88          on_message           ] message: {"jsonrpc": "2.0", "id": 2, "method": "call", "params": [1, "get_api_by_name", ["database_api"]]} 
2967283ms th_a       api.cpp:106                   get_api_by_name      ] found api: database_api
2967283ms th_a       websocket_api.cpp:88          on_message           ] message: {"jsonrpc": "2.0", "id": 3, "method": "call", "params": [1, "get_api_by_name", ["network_broadcast_api"]]} 
2967284ms th_a       api.cpp:106                   get_api_by_name      ] found api: network_broadcast_api
2967284ms th_a       websocket_api.cpp:88          on_message           ] message: {"jsonrpc": "2.0", "id": 4, "method": "call", "params": [0, "get_discussions_by_created", [{"limit": 20, "tag": null}]]} 
2967324ms th_a       database_api.cpp:185          ~database_api_impl   ] freeing database api 1601780752
```

Do I need special steemd configuration?

**Comment by xeroc** [comment]
That's an issue with the node you have defined to use. Please extend the `config.ini` of your node by
```
enable-plugin = account_history                                                                                                                                                       
enable-plugin = follow                                                                                                                                                                
enable-plugin = market_history                                                                                                                                                        
enable-plugin = rivate_message                                                                                                                                                       
enable-plugin = tags                                                                                                                                                                  
                                                                                                                                                                                      
public-api = database_api login_api market_history_api  
```
