### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'get'

### ISSUE THREAD

**Issue by scrawl** [xeroc/piston#14]
Running stream_comments for a long time, I got a crash at some point:

<pre>
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    for c in steem.stream_comments():
  File "/home/scrawl/.local/lib/python3.4/site-packages/steem_piston-0.2.3a-py3.4.egg/piston/steem.py", line 823, in stream_comments
  File "/home/scrawl/.local/lib/python3.4/site-packages/steem_piston-0.2.3a-py3.4.egg/piston/steem.py", line 89, in __init__
AttributeError: 'bool' object has no attribute 'get'
</pre>

I don't know how to reproduce this. It might be a particular post that triggered this error?

**Comment by scrawl** [comment]
I can reproduce this when starting from block 3245790:

<pre>
for c in steem.stream_comments(start=3245790):
   pass
</pre>

**Comment by xeroc** [comment]
should be fixed in `develop` branch now
