### ISSUE TITLE
Attempting to add invalid private key will corrupt the piston listaccounts

### ISSUE THREAD

**Issue by Netherdrake** [xeroc/piston#16]
```
~/S/P/S/steemit-key-regen % piston listaccounts
Traceback (most recent call last):
  File "/anaconda3/bin/piston", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.5/site-packages/piston/__main__.py", line 577, in main
    t.add_row(account)
  File "/anaconda3/lib/python3.5/site-packages/prettytable.py", line 818, in add_row
    raise Exception("Row has incorrect number of values, (actual) %d!=%d (expected)" %(len(row),len(self._field_names)))
Exception: Row has incorrect number of values, (actual) 2!=3 (expected)
~/S/P/S/steemit-key-regen % 
```

**Comment by xeroc** [comment]
This has been fixed in the develop branch. Thanks for reporting.

**Comment by xeroc** [comment]
fixed:
https://github.com/xeroc/piston/commit/273933c6084a0693ae317a72e7aa9ea2f5758116
