### ISSUE TITLE
Got error after launching

### ISSUE THREAD

**Issue by cryptid11** [xeroc/piston#17]
```
$ piston web
Traceback (most recent call last):
  File "/usr/local/bin/piston", line 9, in <module>
    load_entry_point('steem-piston==0.2.3a', 'console_scripts', 'piston')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/home/rodomonte/.local/lib/python3.4/site-packages/steem_piston-0.2.3a-py3.4.egg/piston/__main__.py", line 9, in <module>
    from .storage import configStorage as config
  File "/home/rodomonte/.local/lib/python3.4/site-packages/steem_piston-0.2.3a-py3.4.egg/piston/storage.py", line 321, in <module>
    if not configStorage.exists_table():
  File "/home/rodomonte/.local/lib/python3.4/site-packages/steem_piston-0.2.3a-py3.4.egg/piston/storage.py", line 120, in exists_table
    connection = sqlite3.connect(sqlDataBaseFile)
sqlite3.OperationalError: unable to open database file

```

**Comment by xeroc** [comment]
fixed: https://github.com/xeroc/piston/commit/a9f666e3c7cf25c880cceefaca26eb6d29b6f290
