### ISSUE TITLE
TypeError: can't concat bytes to str

### ISSUE THREAD

**Issue by Wingie** [xeroc/piston#21]
echo "https://wingztv.com" | piston post --author "moridin007" --category "spam" --title "testing python api plz ignore" --permlink "Hash-of-the-file123"

```
Traceback (most recent call last):
  File "/.[venv]../bin/piston", line 11, in <module>
    sys.exit(main())
  File "/.[venv]../lib/python3.4/site-packages/piston/__main__.py", line 621, in main
    meta, body = yaml_parse_file(args, initial_content=post)
  File "/.[venv]../lib/python3.4/site-packages/piston/utils.py", line 62, in yaml_parse_file
    delete=False
  File "/.[venv]../lib/python3.4/tempfile.py", line 599, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
  File "/.[venv]../lib/python3.4/tempfile.py", line 337, in _mkstemp_inner
    file = _os.path.join(dir, pre + name + suf)
TypeError: can't concat bytes to str
```

im getting the error when i try and use the commadn line client from pip3 install

**Comment by xeroc** [comment]
This has already been fixed in the 0.2.3b
