### ISSUE TITLE
Unable to run command 'piston'

### ISSUE THREAD

**Issue by kadnan** [xeroc/piston#24]
I have installed requirement:

```
Adnans-MBP:~ AdnanAhmad$ pip list | grep graph
cryptography (1.4)
graphenelib (0.4.3)
```

But when I run `piston` I get the error:

```
Traceback (most recent call last):
  File "/anaconda3/anaconda/lib/python3.5/site-packages/steembase/__init__.py", line 3, in <module>
    from graphenebase.account import PrivateKey, PublicKey, Address, BrainKey
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/anaconda3/anaconda/lib/python3.5/site-packages/graphenelib-0.4.3-py3.5.egg/graphenebase/__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/anaconda3/anaconda/lib/python3.5/site-packages/graphenelib-0.4.3-py3.5.egg/graphenebase/bip38.py", line 4, in <module>
  File "/anaconda3/anaconda/lib/python3.5/site-packages/scrypt.py", line 11, in <module>
    _scrypt = cdll.LoadLibrary(imp.find_module('_scrypt')[1])
  File "/anaconda3/anaconda/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "/anaconda3/anaconda/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/anaconda3/anaconda/lib/python3.5/site-packages/_scrypt.cpython-35m-darwin.so, 6): Library not loaded: libcrypto.1.0.0.dylib
  Referenced from: /anaconda3/anaconda/lib/python3.5/site-packages/_scrypt.cpython-35m-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/anaconda/bin/piston", line 7, in <module>
    from piston.__main__ import main
  File "/anaconda3/anaconda/lib/python3.5/site-packages/piston/__main__.py", line 7, in <module>
    from steembase import PrivateKey, PublicKey, Address
  File "/anaconda3/anaconda/lib/python3.5/site-packages/steembase/__init__.py", line 8, in <module>
    raise ImportError("Please install 'graphenelibs'")
ImportError: Please install 'graphenelibs'
```

**Comment by xeroc** [comment]
there seems to be something wrong with the `scrypt` package from pip. Please try to reinstall `script`

**Comment by kadnan** [comment]
@xeroc reinstalled, same error.

**Comment by kadnan** [comment]
@xeroc Can you check at your end?

**Comment by xeroc** [comment]
Please try the new piston 0.3  .. it comes with a different default dependency

**Comment by shawnpringle** [comment]
I get the same error after following the install instructions for 0.3 and  trying to run pre -0.3 piston code.  When I run the 0.3 piston code I get a 500 error on my first browse.  Do I need to update the submodules somehow?

**Comment by shawnpringle** [comment]
I did the following:

> pip3 install -r requirements-web.txt --user --upgrade

I run with : "python3 piston.py web"

Now, the error is:  ImportError: No module named 'steembase.account'

**Comment by xeroc** [comment]
you need to upgrate `steem`

    pip3 install steem --upgrade
