### ISSUE TITLE
Better handling of BroadcastingError, more verbose log messages

### ISSUE THREAD

**Issue by noisy** [xeroc/piston#28]
It is typical scenario, to use new account for testing piston library. Such account will not have a lot of STEEM, so it will be very easy to encounter various problems with limits.

Example error message presented by Steemit:

> (now - auth.last_root_post) > STEEMIT_MIN_ROOT_COMMENT_INTERVAL: You may only post once every 5 minutes

in this case, piston library shows:
```
Traceback (most recent call last):
  File "/opt/pycharm-2016.1.4/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/noisy/.virtualenvs/SteemTranslate/lib/python3.4/site-packages/piston/steem.py", line 423, in post
    return self.executeOp(op, wif)
  File "/home/noisy/.virtualenvs/SteemTranslate/lib/python3.4/site-packages/piston/steem.py", line 284, in executeOp
    raise BroadcastingError
piston.steem.BroadcastingError
```

**Comment by xeroc** [comment]
I totally agree .. I should start parsing the error messages and give a more detailed exception
