### ISSUE TITLE
[Piston.web] Exception: Invalid choice of '--sort'!

### ISSUE THREAD

**Issue by cryptomental** [xeroc/piston#30]
Hi @xeroc  it seems I am one of the Alpha testers as well ;-)

```
[2016-08-04 10:32:44,539] ERROR in app: Exception on /browse/steem [GET]
Traceback (most recent call last):
  File "/home/piston/.local/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/piston/.local/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/piston/.local/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/piston/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/piston/.local/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/piston/.local/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/piston/.local/lib/python3.5/site-packages/steem_piston-0.2.3b0-py3.5.egg/piston/web_views.py", line 215, in browse
    start=start
  File "/home/piston/.local/lib/python3.5/site-packages/steem_piston-0.2.3b0-py3.5.egg/piston/steem.py", line 863, in get_posts
    raise Exception("Invalid choice of '--sort'!")
Exception: Invalid choice of '--sort'!
Exception on /browse/steem [GET]
```

Steps to reproduce: Visit http://127.0.0.1:5054/browse/steem

**Comment by xeroc** [comment]
Not sure where you got that url .. but the format for urls is like this:

```
@app.route('/browse', defaults={"category": "", "sort": "trending"})
@app.route('/browse/<sort>', defaults={"category": ""})
@app.route('/browse/<sort>/<category>')
```
That means you cannot browse a category/tag without specifying the sorting (e.g. trending, hot, ...)
