### ISSUE TITLE
[Piston.web] Error 500 when accessing replies menu

### ISSUE THREAD

**Issue by jemekite** [xeroc/piston#33]
Error Logs:
```
[2016-08-05 21:42:39,670] ERROR in app: Exception on /@jemekite/replies [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/piston/web_views.py", line 80, in user_replies
    return render_template('user-replies.html', **locals())
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/piston/templates/user-replies.html", line 2, in top-level template code
    {% extends "layout.html" %}
  File "/usr/local/lib/python3.5/dist-packages/piston/templates/layout.html", line 2, in top-level template code
    {% import "bootstrap/google.html" as google %}
  File "/usr/local/lib/python3.5/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/usr/local/lib/python3.5/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/usr/local/lib/python3.5/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/usr/local/lib/python3.5/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/usr/local/lib/python3.5/dist-packages/piston/templates/user-replies.html", line 11, in block "content"
    {{ showPost(post, "reply") }}
  File "/usr/local/lib/python3.5/dist-packages/piston/templates/_macros.html", line 102, in template
    <a href="{{url_for("read", identifier=post.openingPostIdentifier)}}">
  File "/usr/local/lib/python3.5/dist-packages/flask/helpers.py", line 332, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1811, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/helpers.py", line 322, in url_for
    force_external=external)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/routing.py", line 1758, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'read'. Did you forget to specify values ['identifier']?
```
Steps to reproduce: Visit http://127.0.0.1:5054/@jemekite/replies

**Comment by xeroc** [comment]
I fixed this in the `develop` branch .. will be in master in the next release
