### ISSUE TITLE
TypeError: encoding without a string argument

### ISSUE THREAD

**Issue by mahnunchik** [xeroc/piston#37]
```bash
$ piston addkey
Private Key (wif) [Enter to quit]:
Traceback (most recent call last):
  File "/usr/local/bin/piston", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/piston/__main__.py", line 699, in main
    pub = (steem.wallet.addPrivateKey(wifkey))
  File "/usr/local/lib/python3.5/site-packages/piston/wallet.py", line 230, in addPrivateKey
    self.keyStorage.add(self.encrypt_wif(wif), pub)
  File "/usr/local/lib/python3.5/site-packages/piston/wallet.py", line 178, in encrypt_wif
    return format(bip38.encrypt(PrivateKey(wif), self.masterpassword), "encwif")
  File "/Users/User/Library/Python/3.5/lib/python/site-packages/graphenebase/bip38.py", line 57, in encrypt
    key           = scrypt.scrypt(bytes(passphrase, "utf-8"), salt, 16384, 8, 8)
TypeError: encoding without a string argument
```
```bash
$ python3 --version
Python 3.5.2
```

OS X 10.11.6

**Comment by xeroc** [comment]
wow .. that sucks ..  it seems that `pylibscrypt` behaves differently on OS X than on linux and windows ...

you can try install the python module `scrypt` .. with `pip3 install scrypt` .. if the installation goes through it should fix your issue

**Comment by mahnunchik** [comment]
```bash
$ pip3 install scrypt
```
it solved the issue 😉
