### ISSUE TITLE
Error 500 In browser

### ISSUE THREAD

**Issue by Poseidonn77** [xeroc/piston#39]
This is in the terminal;
./piston.py web
/usr/local/lib/python3.5/dist-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.script is deprecated, use flask_script instead.
  .format(x=modname), ExtDeprecationWarning
Lost connection to node during rpcexec(): wss://this.piston.rocks (1/1) Retrying in 0 seconds
[2016-08-08 10:21:16,610] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/webassets/bundle.py", line 536, in _merge_and_apply
    final = filtertool.apply_func(filters_to_run, 'concat', [hunks])
  File "/usr/local/lib/python3.5/dist-packages/webassets/merge.py", line 297, in apply_func
    raise NoFilters()
webassets.merge.NoFilters

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/webassets/bundle.py", line 540, in _merge_and_apply
    final = merge([h for h, _ in hunks])
  File "/usr/local/lib/python3.5/dist-packages/webassets/merge.py", line 176, in merge
    return MemoryHunk(separator.join([h.data() for h in hunks]))
  File "/usr/local/lib/python3.5/dist-packages/webassets/merge.py", line 176, in <listcomp>
    return MemoryHunk(separator.join([h.data() for h in hunks]))
  File "/usr/local/lib/python3.5/dist-packages/webassets/merge.py", line 77, in data
    f = open(self.filename, 'r', encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: '/home/martin/Documents/piston/piston/static/libs/sliptree-bootstrap-tokenfield/dist/css/bootstrap-tokenfield.min.css'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/martin/Documents/piston/piston/web_views.py", line 55, in index
    return render_template('index.html', **locals())
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/martin/Documents/piston/piston/templates/index.html", line 2, in top-level template code
    {% extends "layout.html" %}
  File "/home/martin/Documents/piston/piston/templates/layout.html", line 2, in top-level template code
    {% import "bootstrap/google.html" as google %}
  File "/usr/local/lib/python3.5/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/usr/local/lib/python3.5/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/usr/local/lib/python3.5/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 6, in block "html"
    {%- block head %}
  File "/usr/local/lib/python3.5/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 13, in block "head"
    {%- block styles %}
  File "/home/martin/Documents/piston/piston/templates/layout.html", line 14, in block "styles"
    {% assets "css_libs" %}
  File "/usr/local/lib/python3.5/dist-packages/webassets/ext/jinja2.py", line 186, in _render_assets
    urls = bundle.urls()
  File "/usr/local/lib/python3.5/dist-packages/webassets/bundle.py", line 787, in urls
    urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/webassets/bundle.py", line 746, in _urls
    *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/webassets/bundle.py", line 600, in _build
    force, disable_cache=disable_cache, extra_filters=extra_filters)
  File "/usr/local/lib/python3.5/dist-packages/webassets/bundle.py", line 546, in _merge_and_apply
    raise BuildError(e)
webassets.exceptions.BuildError: [Errno 2] No such file or directory: '/home/martin/Documents/piston/piston/static/libs/sliptree-bootstrap-tokenfield/dist/css/bootstrap-tokenfield.min.css'
Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/webassets/bundle.py", line 536, in _merge_and_apply
    final = filtertool.apply_func(filters_to_run, 'concat', [hunks])
  File "/usr/local/lib/python3.5/dist-packages/webassets/merge.py", line 297, in apply_func
    raise NoFilters()
webassets.merge.NoFilters

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/webassets/bundle.py", line 540, in _merge_and_apply
    final = merge([h for h, _ in hunks])
  File "/usr/local/lib/python3.5/dist-packages/webassets/merge.py", line 176, in merge
    return MemoryHunk(separator.join([h.data() for h in hunks]))
  File "/usr/local/lib/python3.5/dist-packages/webassets/merge.py", line 176, in <listcomp>
    return MemoryHunk(separator.join([h.data() for h in hunks]))
  File "/usr/local/lib/python3.5/dist-packages/webassets/merge.py", line 77, in data
    f = open(self.filename, 'r', encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: '/home/martin/Documents/piston/piston/static/libs/sliptree-bootstrap-tokenfield/dist/css/bootstrap-tokenfield.min.css'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/martin/Documents/piston/piston/web_views.py", line 55, in index
    return render_template('index.html', **locals())
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/martin/Documents/piston/piston/templates/index.html", line 2, in top-level template code
    {% extends "layout.html" %}
  File "/home/martin/Documents/piston/piston/templates/layout.html", line 2, in top-level template code
    {% import "bootstrap/google.html" as google %}
  File "/usr/local/lib/python3.5/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/usr/local/lib/python3.5/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/usr/local/lib/python3.5/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 6, in block "html"
    {%- block head %}
  File "/usr/local/lib/python3.5/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 13, in block "head"
    {%- block styles %}
  File "/home/martin/Documents/piston/piston/templates/layout.html", line 14, in block "styles"
    {% assets "css_libs" %}
  File "/usr/local/lib/python3.5/dist-packages/webassets/ext/jinja2.py", line 186, in _render_assets
    urls = bundle.urls()
  File "/usr/local/lib/python3.5/dist-packages/webassets/bundle.py", line 787, in urls
    urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/webassets/bundle.py", line 746, in _urls
    *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/webassets/bundle.py", line 600, in _build
    force, disable_cache=disable_cache, extra_filters=extra_filters)
  File "/usr/local/lib/python3.5/dist-packages/webassets/bundle.py", line 546, in _merge_and_apply
    raise BuildError(e)
webassets.exceptions.BuildError: [Errno 2] No such file or directory: '/home/martin/Documents/piston/piston/static/libs/sliptree-bootstrap-tokenfield/dist/css/bootstrap-tokenfield.min.css'
2016-08-08 10:21:16,610 - piston.web_app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/webassets/bundle.py", line 536, in _merge_and_apply
    final = filtertool.apply_func(filters_to_run, 'concat', [hunks])
  File "/usr/local/lib/python3.5/dist-packages/webassets/merge.py", line 297, in apply_func
    raise NoFilters()
webassets.merge.NoFilters

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/webassets/bundle.py", line 540, in _merge_and_apply
    final = merge([h for h, _ in hunks])
  File "/usr/local/lib/python3.5/dist-packages/webassets/merge.py", line 176, in merge
    return MemoryHunk(separator.join([h.data() for h in hunks]))
  File "/usr/local/lib/python3.5/dist-packages/webassets/merge.py", line 176, in <listcomp>
    return MemoryHunk(separator.join([h.data() for h in hunks]))
  File "/usr/local/lib/python3.5/dist-packages/webassets/merge.py", line 77, in data
    f = open(self.filename, 'r', encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: '/home/martin/Documents/piston/piston/static/libs/sliptree-bootstrap-tokenfield/dist/css/bootstrap-tokenfield.min.css'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/martin/Documents/piston/piston/web_views.py", line 55, in index
    return render_template('index.html', **locals())
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/martin/Documents/piston/piston/templates/index.html", line 2, in top-level template code
    {% extends "layout.html" %}
  File "/home/martin/Documents/piston/piston/templates/layout.html", line 2, in top-level template code
    {% import "bootstrap/google.html" as google %}
  File "/usr/local/lib/python3.5/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/usr/local/lib/python3.5/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/usr/local/lib/python3.5/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 6, in block "html"
    {%- block head %}
  File "/usr/local/lib/python3.5/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 13, in block "head"
    {%- block styles %}
  File "/home/martin/Documents/piston/piston/templates/layout.html", line 14, in block "styles"
    {% assets "css_libs" %}
  File "/usr/local/lib/python3.5/dist-packages/webassets/ext/jinja2.py", line 186, in _render_assets
    urls = bundle.urls()
  File "/usr/local/lib/python3.5/dist-packages/webassets/bundle.py", line 787, in urls
    urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/webassets/bundle.py", line 746, in _urls
    *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/webassets/bundle.py", line 600, in _build
    force, disable_cache=disable_cache, extra_filters=extra_filters)
  File "/usr/local/lib/python3.5/dist-packages/webassets/bundle.py", line 546, in _merge_and_apply
    raise BuildError(e)
webassets.exceptions.BuildError: [Errno 2] No such file or directory: '/home/martin/Documents/piston/piston/static/libs/sliptree-bootstrap-tokenfield/dist/css/bootstrap-tokenfield.min.css'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/gevent/baseserver.py", line 25, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python3.5/dist-packages/gevent/pywsgi.py", line 1253, in handle
    handler.handle()
  File "/usr/local/lib/python3.5/dist-packages/gevent/pywsgi.py", line 443, in handle
    result = self.handle_one_request()
  File "/usr/local/lib/python3.5/dist-packages/gevent/pywsgi.py", line 658, in handle_one_request
    self.handle_one_response()
  File "/usr/local/lib/python3.5/dist-packages/gevent/pywsgi.py", line 916, in handle_one_response
    self.log_request()
  File "/usr/local/lib/python3.5/dist-packages/geventwebsocket/handler.py", line 236, in log_request
    if '101' not in self.status:
TypeError: a bytes-like object is required, not 'str'
<Greenlet at 0x7f309d8c0d58: _handle_and_close_when_done(<bound method WSGIServer.handle of <WSGIServer at , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed]  object, fd=-1, )> failed with TypeError

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/gevent/baseserver.py", line 25, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python3.5/dist-packages/gevent/pywsgi.py", line 1253, in handle
    handler.handle()
  File "/usr/local/lib/python3.5/dist-packages/gevent/pywsgi.py", line 443, in handle
    result = self.handle_one_request()
  File "/usr/local/lib/python3.5/dist-packages/gevent/pywsgi.py", line 658, in handle_one_request
    self.handle_one_response()
  File "/usr/local/lib/python3.5/dist-packages/gevent/pywsgi.py", line 916, in handle_one_response
    self.log_request()
  File "/usr/local/lib/python3.5/dist-packages/geventwebsocket/handler.py", line 236, in log_request
    if '101' not in self.status:
TypeError: a bytes-like object is required, not 'str'
<Greenlet at 0x7f309cc2c5a0: _handle_and_close_when_done(<bound method WSGIServer.handle of <WSGIServer at , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed]  object, fd=-1, )> failed with TypeError

**Comment by xeroc** [comment]
could you please run

    make install-user

and then run the

    ~/.local/bin/piston web

You get the same or a different error, then?

**Comment by Poseidonn77** [comment]
The same thing. I am running ./pistion web . same issue.... Could it be that you need it to run just "piston web" without "./"?

**Comment by Poseidonn77** [comment]
I ran ~/.local/bin/piston web as well same . will go over everything and check. could be my side

**Comment by proctologic** [comment]
witness@witness:~/piston$ ~/.local/bin/piston web
/home/witness/.local/lib/python3.5/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.script is deprecated, use flask_script instead.
  .format(x=modname), ExtDeprecationWarning
WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
 * Running on http://127.0.0.1:5054/ (Press CTRL+C to quit)

**Comment by Poseidonn77** [comment]
Didn't upgrade the dependancies to -->
https://steemit.com/piston/@xeroc/changelog-piston-0-3

And now it's A okay.
