### ISSUE TITLE
Sending 1.001 SBD

### ISSUE THREAD

**Issue by skzap** [xeroc/piston#49]
`piston transfer --account heimindanger steembingo 1.001 SBD`

gives out the following error output

`Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/piston/steem.py", line 347, in executeOp
    self.rpc.broadcast_transaction(tx, api="network_broadcast")
  File "/usr/lib/python3.5/site-packages/grapheneapi/graphenewsrpc.py", line 379, in method
    r = self.rpcexec(query)
  File "/usr/lib/python3.5/site-packages/grapheneapi/graphenewsrpc.py", line 346, in rpcexec
    raise RPCError(ret['error']['message'])
grapheneapi.graphenewsrpc.RPCError: 3030001 tx_missing_active_auth: missing required active authority
Missing Active Authority heimindanger`

I am not missing this key, and I have enough money to transfer. Transfering 1.002 SBD works fine. Same bug happens with any receiver / recipient.

**Comment by xeroc** [comment]
Fixed
https://github.com/xeroc/python-steemlib/commit/34a7525cee119ec9b24a99577ede2d54466fca0e
