### ISSUE TITLE
Ubuntu 6 error: pip3 install steem-piston

### ISSUE THREAD

**Issue by jcalfee** [xeroc/piston#63]
There is probably something wrong with my Python environment.  I really have not done much other than install the python3 and python-pip3 packages.  Any idea what is going on here?
```
pip3 install steem-piston
Collecting steem-piston
  Using cached steem_piston-0.3.3-py3-none-any.whl
Collecting steem>=0.2.2 (from steem-piston)
  Using cached steem-0.2.2-py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): pycrypto==2.6.1 in /usr/local/lib/python3.5/dist-packages (from steem-piston)
Requirement already satisfied (use --upgrade to upgrade): appdirs==1.4.0 in /usr/local/lib/python3.5/dist-packages (from steem-piston)
Collecting prettytable==0.7.2 (from steem-piston)
Requirement already satisfied (use --upgrade to upgrade): colorama==0.3.6 in /usr/local/lib/python3.5/dist-packages (from steem-piston)
Requirement already satisfied (use --upgrade to upgrade): python-frontmatter==0.2.1 in /usr/local/lib/python3.5/dist-packages (from steem-piston)
Requirement already satisfied (use --upgrade to upgrade): diff-match-patch==20121119 in /usr/local/lib/python3.5/dist-packages (from steem-piston)
Collecting graphenelib>=0.4.5 (from steem>=0.2.2->steem-piston)
  Using cached graphenelib-0.4.5-py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): websockets==2.0 in /usr/local/lib/python3.5/dist-packages (from steem>=0.2.2->steem-piston)
Requirement already satisfied (use --upgrade to upgrade): PyYAML in /usr/local/lib/python3.5/dist-packages (from python-frontmatter==0.2.1->steem-piston)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python3/dist-packages (from python-frontmatter==0.2.1->steem-piston)
Collecting websocket-client==0.37.0 (from graphenelib>=0.4.5->steem>=0.2.2->steem-piston)
Requirement already satisfied (use --upgrade to upgrade): ecdsa==0.13 in /usr/local/lib/python3.5/dist-packages (from graphenelib>=0.4.5->steem>=0.2.2->steem-piston)
Collecting requests==2.10.0 (from graphenelib>=0.4.5->steem>=0.2.2->steem-piston)
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting pylibscrypt==1.5.3 (from graphenelib>=0.4.5->steem>=0.2.2->steem-piston)
Requirement already satisfied (use --upgrade to upgrade): asyncio in /usr/local/lib/python3.5/dist-packages (from websockets==2.0->steem>=0.2.2->steem-piston)
Installing collected packages: websocket-client, requests, pylibscrypt, graphenelib, steem, prettytable, steem-piston
Exception:
Traceback (most recent call last):
  File "/home/jcalfee/.local/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/jcalfee/.local/lib/python3.5/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/home/jcalfee/.local/lib/python3.5/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/home/jcalfee/.local/lib/python3.5/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/jcalfee/.local/lib/python3.5/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/home/jcalfee/.local/lib/python3.5/site-packages/pip/wheel.py", line 378, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/home/jcalfee/.local/lib/python3.5/site-packages/pip/wheel.py", line 324, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/lib/python3.5/shutil.py", line 115, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/local/bin/wsdump.py'
```

**Comment by Poseidonn77** [comment]
"sudo pip3 install steem-piston"

That worked for me

**Comment by xeroc** [comment]
> PermissionError: [Errno 13] Permission denied: '/usr/local/bin/wsdump.py'

As user you can't write into that directory.
Either install as `root` or append `--user` to the `pip` call ..
The executable will then be installed into `~/.local/bin`

**Comment by jcalfee** [comment]
I found a workaround: `sudo pip3 install steem-piston`
