### ISSUE TITLE
add colorama to requirements

### ISSUE THREAD

**Issue by metasyn** [xeroc/piston#7]
```
$ ./piston read @ash/if-you-did-not-change-your-password-after-the-hack-do-it-now
Traceback (most recent call last):
  File "./piston", line 11, in <module>
    sys.exit(main())
  File "/Users/aljohnson/Library/Python/3.5/lib/python/site-packages/piston/__main__.py", line 691, in main
    body = markdownify(post["body"])
  File "/Users/aljohnson/Library/Python/3.5/lib/python/site-packages/piston/ui.py", line 82, in markdownify
    import colorama
ImportError: No module named 'colorama'
```

**Comment by songproducer** [comment]
pip3 install colorama
