### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by clayop** [xeroc/piston#78]
>>> from piston.steem import Steem
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/piston/steem.py", line 4, in <module>
    from steem.steem import ExchangeConfig as ExchangeConfigSteem
ImportError: cannot import name 'ExchangeConfig'

**Comment by clayop** [comment]
This error occurs when I install steem and steem-piston together

**Comment by pmartynov** [comment]
Hey @clayop , `from steem import Steem` should work.

**Comment by xeroc** [comment]
Sorry for that .. was my fault .. please give me a little time and install version 0.4.1 that I will release shortly
