### ISSUE TITLE
debian jessie runtime SyntaxError failure with python3.4

### ISSUE THREAD

**Issue by sneak** [xeroc/piston#86]
`sudo apt-get install -y python3-pip`
`pip3 install --user steem-piston`

everything installs fine. then:

```
jp@docker-machine-dev:~$ piston
Traceback (most recent call last):
  File "/home/jp/.local/bin/piston", line 7, in <module>
    from piston.__main__ import main
  File "/home/jp/.local/lib/python3.4/site-packages/piston/__main__.py", line 11, in <module>
    from steem.storage import configStorage as config
  File "/home/jp/.local/lib/python3.4/site-packages/steem/__init__.py", line 1, in <module>
    from .steem import Steem
  File "/home/jp/.local/lib/python3.4/site-packages/steem/steem.py", line 632
    **s,
       ^
SyntaxError: invalid syntax
jp@docker-machine-dev:~$
```

**Comment by xeroc** [comment]
We fixed this already .. will be deployed with the next release
