### ISSUE TITLE
Issuing when running for first time (AccountDoesNotExistsException)

### ISSUE THREAD

**Issue by gitbase1** [xeroc/piston#88]
Ubuntu 

error, 

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/piston", line 7, in <module>
    from piston.__main__ import main
  File "/home/ubuntu/.local/lib/python3.5/site-packages/steem_piston-0.4.3a0-py3.5.egg/piston/__main__.py", line 40, in <module>
    from steem.steem import AccountDoesNotExistsException
ImportError: cannot import name 'AccountDoesNotExistsException'

**Comment by gitbase1** [comment]
Thanks, that worked.  The "piston" command now works.  But now the issue pops up with a custom script,  made a simple vote.py

python3 vote.py

code:

from piston.steem import Steem
steem = Steem()
print(steem.rpc.get_account("xeroc"))

error:

Traceback (most recent call last):
  File "vote.py", line 1, in <module>
    from piston.steem import Steem
  File "/home/ubuntu/piston/piston/steem.py", line 5, in <module>
    from steem.steem import AccountDoesNotExistsException
ImportError: cannot import name 'AccountDoesNotExistsException'

**Comment by gitbase1** [comment]
seem to have fixed with 

from steem import Steem
