### ISSUE TITLE
AttributeError: 'Post' object has no attribute 'url'

### ISSUE THREAD

**Issue by scrawl** [xeroc/piston#9]
I get an error running the stream-comments example:

<pre>
python3 stream-comments.py

Traceback (most recent call last):
  File "stream-comments.py", line 6, in <module>
    for c in steem.stream_comments():
  File "/home/scrawl/.local/lib/python3.4/site-packages/steem_piston-0.2.2b-py3.4.egg/piston/steem.py", line 756, in stream_comments
  File "/home/scrawl/.local/lib/python3.4/site-packages/steem_piston-0.2.2b-py3.4.egg/piston/steem.py", line 77, in __init__
  File "/home/scrawl/.local/lib/python3.4/site-packages/steem_piston-0.2.2b-py3.4.egg/piston/steem.py", line 80, in _getOpeningPost
AttributeError: 'Post' object has no attribute 'url'
</pre>

**Comment by xeroc** [comment]
That error has been fixed in the new release. Thanks for the report
